################################### Latvian language #####################################
[lv]
languageName = "Latviešu"
languageCode = "lv-lv"
contentDir = "content/lv"
weight = 1

################################### English language #####################################
[en]
languageName = "English"
languageCode = "en-us"
contentDir = "content/en"
weight = 2

################################### Russian language #####################################
[ru]
languageName = "Русский"
languageCode = "ru-ru"
contentDir = "content/ru"
weight = 3