############# Russian navigation ##############

# main menu
[[main]]
name = "Главная"
url = ""
weight = 1

[[main]]
name = "Решения"
url = "/solutions"
weight = 2
hasChildren = true

  [[main]]
  parent = "Решения"
  name = "Торговля и услуги"
  url = "/solutions/retail-services"
  weight = 1

  [[main]]
  parent = "Решения"
  name = "Автомойки и спецпроекты"
  url = "/solutions/custom-projects"
  weight = 2

  [[main]]
  parent = "Решения"
  name = "Услуги и цены"
  url = "/solutions/services-and-prices"
  weight = 2

[[main]]
name = "Программное обеспечение"
url = "/software"
weight = 3

[[main]]
name = "Оборудование"
url = "/hardware"
weight = 4
hasChildren = true

  # [[main]]
  # parent = "Оборудование"
  # name = "POS Моноблоки"
  # url = "/hardware/monoblocks/"
  # weight = 1

  # [[main]]
  # parent = "Оборудование"
  # name = "Чековые принтеры"
  # url = "/hardware/printers/"
  # weight = 2

  [[main]]
  parent = "Оборудование"
  name = "POS-терминалы"
  url = "/hardware/pos-systems/"
  weight = 3

  # [[main]]
  # parent = "Оборудование"
  # name = "Киоски самообслуживания"
  # url = "/hardware/kiosks/"
  # weight = 4

  # [[main]]
  # parent = "Оборудование"
  # name = "POS Периферия"
  # url = "/hardware/peripherals/"
  # weight = 5

[[main]]
name = "Контакты"
url = "contact/"
weight = 5






# footer menu
[[footer]]
name = "Часто задаваемые вопросы"
url = "faq/"
weight = 1

[[footer]]
name = "Инструкции"
url = "instructions/"
weight = 2

[[footer]]
name = "О нас"
url = "about/"
weight = 3


[[footer]]
name = "Контакты"
url = "contact/"
weight = 4

[[footer]]
name = "Услуги и цены"
url = "/solutions/services-and-prices"
weight = 5

[[footer]]
name = "Политика конфиденциальности"
url = "terms-and-conditions/"
weight = 6