############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "Solutions"
url = "/solutions"
weight = 2
hasChildren = true

  [[main]]
  parent = "Solutions"
  name = "Retail & Services"
  url = "/solutions/retail-services"
  weight = 1

  [[main]]
  parent = "Solutions"
  name = "Car Washes & Custom Projects"
  url = "/solutions/custom-projects"
  weight = 2

  [[main]]
  parent = "Solutions"
  name = "Services & Prices"
  url = "/solutions/services-and-prices"
  weight = 3

[[main]]
name = "Software"
url = "/software"
weight = 3

[[main]]
name = "Products"
url = "/product"
weight = 4
hasChildren = true

  [[main]]
  parent = "Products"
  name = "Customer Displays"
  url = "/product/displays/"
  weight = 1

  [[main]]
  parent = "Products"
  name = "Peripherals"
  url = "/product/periphery/"
  weight = 2

  [[main]]
  parent = "Products"
  name = "POS Terminals"
  url = "/product/pos-systems/"
  weight = 3

  [[main]]
  parent = "Products"
  name = "Printers"
  url = "/product/printers/"
  weight = 4

[[main]]
name = "Contacts"
url = "contact/"
weight = 5






# footer menu
[[footer]]
name = "FAQ - Frequently Asked Questions"
url = "faq/"
weight = 1

[[footer]]
name = "Instructions"
url = "instructions/"
weight = 2

[[footer]]
name = "About Us"
url = "about/"
weight = 3


[[footer]]
name = "Contacts"
url = "contact/"
weight = 4

[[footer]]
name = "Services & Prices"
url = "/solutions/services-and-prices"
weight = 5

[[footer]]
name = "Privacy Policy"
url = "terms-and-conditions/"
weight = 6