############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "Solutions"
url = "/solutions"
weight = 2
hasChildren = true

  [[main]]
  parent = "Solutions"
  name = "Retail and Services"
  url = "/solutions/retail-services"
  weight = 1

  [[main]]
  parent = "Solutions"
  name = "Car Washes and Custom Projects"
  url = "/solutions/custom-projects"
  weight = 2

  [[main]]
  parent = "Solutions"
  name = "Services and Prices"
  url = "/solutions/services-and-prices"
  weight = 2

[[main]]
name = "Software"
url = "/software"
weight = 3

[[main]]
name = "Hardware"
url = "/hardware"
weight = 4
hasChildren = true

  # [[main]]
  # parent = "Hardware"
  # name = "POS Monoblocks"
  # url = "/products/monoblocks/"
  # weight = 1

  # [[main]]
  # parent = "Hardware"
  # name = "Receipt Printers"
  # url = "/products/printers/"
  # weight = 2

  # [[main]]
  # parent = "Hardware"
  # name = "POS Systems"
  # url = "/products/pos-systems/"
  # weight = 3

  # [[main]]
  # parent = "Hardware"
  # name = "Self-Service Kiosks"
  # url = "/products/kiosks/"
  # weight = 4

  # [[main]]
  # parent = "Hardware"
  # name = "POS Peripherals"
  # url = "/products/peripherals/"
  # weight = 5

[[main]]
name = "Contact"
url = "contact/"
weight = 5

# footer menu
[[footer]]
name = "FAQ - Frequently Asked Questions"
url = "faq/"
weight = 1

[[footer]]
name = "Instructions"
url = "instructions/"
weight = 2

[[footer]]
name = "About Us"
url = "about/"
weight = 3

[[footer]]
name = "Contact"
url = "contact/"
weight = 4

[[footer]]
name = "Services and Prices"
url = "/solutions/services-and-prices"
weight = 5

[[footer]]
name = "Privacy Policy"
url = "terms-and-conditions/"
weight = 6