############# Latvian navigation ##############

# main menu
[[main]]
name = "Sākums"
url = ""
weight = 1

[[main]]
name = "Risinājumi"
url = "/solutions"
weight = 2
hasChildren = true

  [[main]]
  parent = "Risinājumi"
  name = "Tirdzniecība un pakalpojumi"
  url = "/solutions/retail-services"
  weight = 1

  [[main]]
  parent = "Risinājumi"
  name = "Automazgātavas un specprojekti"
  url = "/solutions/custom-projects"
  weight = 2

  [[main]]
  parent = "Risinājumi"
  name = "Pakalpojumi un cenas"
  url = "/solutions/services-and-prices"
  weight = 2

[[main]]
name = "Programmatūra"
url = "/software"
weight = 3

[[main]]
name = "Iekārtas"
url = "/hardware"
weight = 4
hasChildren = true

  # [[main]]
  # parent = "Iekārtas"
  # name = "POS Monobloki"
  # url = "/products/monoblocks/"
  # weight = 1

  # [[main]]
  # parent = "Iekārtas"
  # name = "Čeku printeri"
  # url = "/products/printers/"
  # weight = 2

  # [[main]]
  # parent = "Iekārtas"
  # name = "Kases sistēmas"
  # url = "/products/pos-systems/"
  # weight = 3

  # [[main]]
  # parent = "Iekārtas"
  # name = "Pašapkalpošanās kioski"
  # url = "/products/kiosks/"
  # weight = 4

  # [[main]]
  # parent = "Iekārtas"
  # name = "POS Perifērija"
  # url = "/products/peripherals/"
  # weight = 5

[[main]]
name = "Kontakti"
url = "contact/"
weight = 5






# footer menu
[[footer]]
name = "B.U.J. - Biežāk uzdotie jautājumi"
url = "faq/"
weight = 1

[[footer]]
name = "Instrukcijas"
url = "instructions/"
weight = 2

[[footer]]
name = "Par mums"
url = "about/"
weight = 3


[[footer]]
name = "Kontakti"
url = "contact/"
weight = 4

[[footer]]
name = "Pakalpojumi un cenas"
url = "/solutions/services-and-prices"
weight = 5

[[footer]]
name = "Privātuma politika"
url = "terms-and-conditions/"
weight = 6
