############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

# [[main]]
# name = "About"
# url = "about/"
# weight = 2


[[main]]
name = "Terms & Conditions"
url = "terms-and-conditions/"
weight = 3

[[main]]
weight = 4
name = "Products"
hasChildren = true

  [[main]]
  parent = "Products"
  name = "POS Terminals"
  url = "/products/monoblocks/"
  weight = 1

  [[main]]
  parent = "Products"
  name = "Receipt Printers"
  url = "/products/printers/"
  weight = 2

  [[main]]
  parent = "Products"
  name = "POS Systems"
  url = "/products/pos-systems/"
  weight = 3

  [[main]]
  parent = "Products"
  name = "Self-Service Kiosks"
  url = "/products/kiosks/"
  weight = 4

  [[main]]
  parent = "Products"
  name = "POS Peripherals"
  url = "/products/peripherals/"
  weight = 5

[[main]]
name = "Pricing"
url = "pricing/"
weight = 5

[[main]]
name = "Contacts"
url = "contact/"
weight = 6






# footer menu
[[footer]]
name = "Contacts"
url = "contact/"
weight = 1

[[footer]]
name = "Pricing"
url = "pricing/"
weight = 2

[[footer]]
name = "Products"
url = "products/"
weight = 3

[[footer]]
name = "Terms & Conditions"
url = "terms-and-conditions/"
weight = 4
