#################### default parameters ################################
# favicon module: https://github.com/gethugothemes/hugo-modules/tree/master/images#favicon-implementation
favicon = "images/favicon.png"
# logo module: https://github.com/gethugothemes/hugo-modules/tree/master/images#logo-implementation
logo = "images/logo.png"
# use `px` or `x` with logo_width, example: "100px".
# Note: logo_width is not work with .svg file
logo_width = "120px"
# if logo_webp set false, it will not generate WEBP version of logo | default is true
logo_webp = true
# logo text will only show when logo is missing.
logo_text = "Alpos"

# footer information
footer_info = "footer_info" # see i18n files for translation

# contact form action
contact_form_action = "" # contact form works with https://formspree.io

# enable or disable popup module
popup = true

# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>" 
custom_script= "" 

# Main Sections
mainSections= ["blog"]

# contact information
[contact_info]
address = "Biķernieku iela 226–19, Rīga, LV-1079"
office_address = "Ropažu iela 140-320, Rīga, LV-1006"
sia = "SIA ALPOS, reģ. nr. 40103341175"
pvn = "PVN reģ. nr. LV40103341175"
phone = ["+371 29 509 312", "+371 29 204 911"]
email = ["alpos@alpos.lv"]
bank_info = "Swedbank, HABALV22"
bank_account_number = "LV49HABA0551029605087"

# Preloader 
# module: https://github.com/gethugothemes/hugo-modules/tree/master/components/preloader
[preloader]
enable = true
preloader = "images/favicon.png" # use jpg, png, svg or gif format.

# Navigation button
[navigation_button]
enable = true
label = "navigation_button" # see i18n files for translation
link = "/contact"


# seo meta data for OpenGraph / Twitter Card
# seo module: https://github.com/gethugothemes/hugo-modules/tree/master/seo-tools/basic-seo
[metadata]
keywords = ["ALPOS", "POS sistēmas", "kases sistēmas", "kases aparāti", "moderna kases sistēma", "kases sistēmas tirdzniecībai", "kases sistēmas veikalam", "kases sistēmas kafejnīcām", "kases sistēmas bāriem", "kases sistēmas picērijām", "kases sistēmas krodziņiem", "kases sistēmas frizētavām", "kases sistēmas skaistumkopšanas saloniem", "kases sistēmas degvielas uzpildes stacijām"]
description = "ALPOS - VID sertificētas POS sistēmas un aprīkojums kafejnīcām un tirdzniecībai Latvijā"
image = "images/logo.png" # this image will be used as fallback if a page has no image of its own

# matomo tracking: see https://matomo.org/
# matomo module: https://github.com/gethugothemes/hugo-modules/tree/master/seo-tools/matomo-analytics
[matomo]
enable = false
url = "" # your matomo url
id = "" # your matomo id

# baidu analytics: see https://tongji.baidu.com/
# baidu module: https://github.com/gethugothemes/hugo-modules/tree/master/seo-tools/baidu-analytics
[baidu]
enable = false
analytics_id = "" # Your ID

# plausible analytics: see https://plausible.io/
# plausible module: https://github.com/gethugothemes/hugo-modules/tree/master/seo-tools/plausible-analytics
[plausible]
enable = false
domain = "" # yourdomain.com

# counter analytics: see https://counter.dev/setup.html
# counter module: https://github.com/gethugothemes/hugo-modules/tree/master/seo-tools/counter-analytics
[counter]
enable = false
username = "" # your username

# site verifications
# verification module: https://github.com/gethugothemes/hugo-modules/tree/master/seo-tools/site-verifications
[site_verification]
google = "" # Your verification code
bing = "" # Your verification code
baidu = "" # Your verification code
facebook = "" # Your verification code

# crisp chat - module: https://github.com/gethugothemes/hugo-modules/tree/master/components/crisp-chat
[crisp_chat]
enable = false
crisp_website_id = "9aa449e1-9999-422a-938f-8567982eec6d" # replace this code with yours
# Check this video tutorial to get your crisp website ID - https://www.youtube.com/watch?v=nW5UX6iVdFc

# cookies
# cookies module: https://github.com/gethugothemes/hugo-modules/tree/master/components/cookie-consent
[cookies]
enable = true
expire_days = 2

# call-to-action
[cta]
enable = true
title = "cta_title" # see i18n files for translation
content = "cta_content" # see i18n files for translation
button = "cta_button" # see i18n files for translation
button_link = "/contact"
